### ISSUE TITLE
NullReferenceException on run

### ISSUE THREAD

**Issue by pierrediancourt** [stefanprodan/dockerdash#1]
Hi,
 
I'm getting this error using `docker logs dockerdash`

> Hosting environment: Production
> Content root path: /app
> Now listening on: http://*:5050
> Application started. Press Ctrl+C to shut down.
> info: DockerDash.TokenProvider.TokenProviderMiddleware[0]
>       Token generated for admin IP 88.173.8.57 at 11/08/2016 22:31:42 expires after 48 hours
> warn: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[35]
>       No XML encryptor configured. Key {92804b56-ef0c-4103-b8bb-b545948bd11c} may be persisted to storage in unencrypted form.
> fail: DockerDash.DockerService[1001]
>       Object reference not set to an instance of an object.
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at DockerDash.DockerService.<GetHostInfo>d__9.MoveNext()

after i ran the container this way 

> docker run --net=isolated_nw \
> -e DOCKERDASH_USER='admin' \
> -e DOCKERDASH_PASSWORD='changeme' \
> -p 5050:5050 \
> -v /var/run/docker.sock:/var/run/docker.sock \
> --name dockerdash \
> -d stefanprodan/dockerdash

The Error line is displayed in the logs only after logging in.
The same error line is displayed again when i use the Host button in the navbar.
Buttons Host, About and Logout are the only elements displayed. Logout and About work as expected.

In the browser console i get this 
> SignalR: Websocket opened.lib.js:43:3362
> SignalR: webSockets transport connected. Initiating start request.
> SignalR: The start request succeeded. Transitioning to the connected state.
> SignalR: Now monitoring keep alive with a warning timeout of 13333.333333333332, keep alive timeout of 20000 and disconnecting timeout of 30000
> SignalR: Invoking mainhub.GetHost
> SignalR: mainhub.GetHost failed to execute. Error: Object reference not set to an instance of an object.

My docker version is `Docker version 1.11.2, build bac3bae` and running on CoreOS stable.
I'm wondering if there's a problem with mounting the docker.sock into the container because i have some other issues with another project of yours saying that it cannot find docker but that may be a totally different issue.

Anyway i can tell you the /var/run/docker.sock path is valid as the command `ls -lah /var/run/d*` returns me this

> -rw-r--r--. 1 root   root    4 Nov  4 20:05 /var/run/docker.pid
> srw-rw----. 1 docker docker  0 Nov  4 20:05 /var/run/docker.sock

**Comment by stefanprodan** [comment]
Yes this happens because Docker.NET is incompatible with 1.11. I guess it tries to get the Swarm mode node list and since 1.11 doesn't have that property it crashes. It's nothing I can do, Docker.NET doesn't have offer backwards compatibility from one major release to another...

**Comment by pierrediancourt** [comment]
Thanks for you answer, i'll wait some more time so that the stable CoreOS version upgrades its docker version !

**Comment by stefanprodan** [comment]
Going to close this since I can't fix it. Thanks for trying out dockerdash. Let me know if you encounter any problems on CoreOS with Docker 1.12.
